### ISSUE TITLE
Frontend styling

### ISSUE THREAD

**Issue by Runi-VN** [MalteMagnussen/CA3#13]
Must be implemented as a Single Page Application with React and provide:
```
Must be styled 
(use bootstrap unless you have knowledge from somewhere else) to be immediately “presentable”
```

**Comment by MrHardcode** [comment]
How thorough is this meant to be? We've already imported bootstrap and used it on the login/logout buttons. I don't know if we should make more styling or just leave it as it is now.

**Comment by Runi-VN** [comment]
> How thorough is this meant to be?  

I believe anything past vanilla HTML is good enough, considering this is a *startcode* project. (compare it to the ones we have been supplied by teachers)
