### ISSUE TITLE
Provide unit and integration tests, and must be “testable” by Travis

### ISSUE THREAD

**Issue by Runi-VN** [MalteMagnussen/CA3#4]
Should be enough to provide testing of REST-endpoints + default testing from project start code.

**Comment by MalteMagnussen** [comment]
So what, exactly, do I have to test? 

1. The "five" endpoint
2. Login Endpoint
   - How? There isn't a "register user" endpoint I can use to make users. So make a user in the test database, and then test on that I guess?

**Comment by MalteMagnussen** [comment]
Testing Facade Currently.

**Comment by MalteMagnussen** [comment]
#28 is the PR.

**Comment by MalteMagnussen** [comment]
Doing 1-2 hours of testing on REST endpoint. Then continuing sometime tomorrow.
