### ISSUE TITLE
Backend must be deployable using a single maven command

### ISSUE THREAD

**Issue by Runi-VN** [MalteMagnussen/CA3#5]
Taken from [here](https://github.com/HrBjarup/DAT-Week-45/blob/master/05-Friday/Books_Backend/README_proof_of_concept.md):
```mvn clean test -Dremote.user=script_user -Dremote.password=PW_FOR_script_user tomcat7:deploy```

**Comment by Runi-VN** [comment]
Probably tied to #18 in one way or another

**Comment by Runi-VN** [comment]
To be tested individually after final push. Leave feedback here.

**Comment by MalteMagnussen** [comment]
How is it going so far?

**Comment by Runi-VN** [comment]
Confirmed working.
Used the above command on my own fork with this result 
![image](https://user-images.githubusercontent.com/37186286/69013165-64819f80-097d-11ea-9b26-fc5862e5a0d2.png)
![image](https://user-images.githubusercontent.com/37186286/69013170-75caac00-097d-11ea-99c2-cd1b3baa08b0.png)
